import { setupClient } from './setup-client.ts';
import { realmCodes } from './realms.ts';
// SR_USII is the app-wide default realm (see e.g. environment.ts, characters/shared.js's
// merchantHomeRealm), so it stays the pre-selected first option rather than following
// realmCodes' logical I/II/III/... ordering.
const orderedRealmCodes = ['SR_USII', ...realmCodes.filter((code) => code !== 'SR_USII')];
const realmOptions = orderedRealmCodes.map((code) => `<option>${code}</option>`).join('');
export const setupPage = `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Party Console setup</title>
<style>body{font:17px system-ui;background:#101318;color:#f4f4f5;max-width:760px;margin:40px auto;padding:20px}button,input,select,textarea,.button{font:inherit;background:#232933;color:#fff;border:1px solid #8693a6;border-radius:6px;padding:10px;margin:8px 0}button,.button{cursor:pointer}button:hover,.button:hover{background:#38465a;color:#fff;border-color:#b7c7dd}button:disabled{opacity:.6;cursor:default}button:focus-visible,a:focus-visible,select:focus-visible{outline:2px solid #93c5fd;outline-offset:2px}input,textarea,select{box-sizing:border-box;width:100%}textarea{height:110px}a{color:#93c5fd}.button{display:inline-block;text-decoration:none}code{overflow-wrap:anywhere}section{border:1px solid #596579;padding:18px;margin:20px 0}#error{color:#fca5a5;white-space:pre-wrap}#success{color:#86efac}label{display:block}summary{cursor:pointer;color:#bfdbfe}details{margin:12px 0}.session-field{display:flex;gap:8px;align-items:center}.session-field input{flex:1;min-width:0}.session-field button{display:flex;align-items:center;justify-content:center;flex:none;width:46px;height:46px}.session-field svg{width:22px;height:22px}[hidden]{display:none!important}</style></head><body>
<h1>Party Console</h1><p>Connect your account, then choose how you want to play.</p><p id="error" role="status"></p><p id="success" role="status" hidden></p>
<section id="pair" hidden><h2>Pair this browser</h2><p>Open an invitation from an authorized browser or the server startup output.</p><button id="pairButton">Pair browser</button></section>
<main id="settings" hidden><section id="account"><h2>Connect your game account</h2><p>You only need to connect your account once. In Adventure Land, log in to a character, open CODE, paste this line, and click Engage:</p><code>show_json(parent.user_id + "-" + parent.user_auth)</code><p>Copy the displayed session and paste it below.</p>
<label for="session">Game session</label><div class="session-field"><input id="session" type="password" autocomplete="off" autocapitalize="none" spellcheck="false"><button id="toggleSession" type="button" aria-label="Show game session" title="Show game session" aria-controls="session" aria-pressed="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/><path id="sessionSlash" d="m3 3 18 18" style="display:none"/></svg></button></div><label>Realm<select id="realm">${realmOptions}</select></label><button id="connect">Connect account</button></section>
<div id="paths" hidden><section><h2>Link Steam or your browser</h2><p>Answer for the computer running Adventure Land, even if you opened setup on another device.</p>
<label for="placement">Are Adventure Land and Party Console running on the same computer?</label><select id="placement"><option value="">Choose…</option><option value="same">Same computer</option><option value="remote">Different computers</option></select>
<label for="client">How are you playing Adventure Land?</label><select id="client"><option value="">Choose…</option><option value="windows-steam">Windows — Steam client</option><option value="windows-browser">Windows — browser</option><option value="linux-steam">Linux — Steam client</option><option value="linux-browser">Linux — browser</option></select>
<div id="instructions" hidden><p>Browser instructions support Chrome, Chromium, Edge, and Firefox. For another browser, use HTTPS.</p>
<button id="fallback" hidden>Use HTTPS instead</button>
<div id="tlsSteps" hidden><h3>1. Trust this Party Console on your game computer</h3><details><summary>Advanced: correct the server address</summary><label for="override">Console address</label><input id="override" placeholder="Use the address you opened setup with"><p>Keep the server’s LAN address stable with a router DHCP reservation. If it changes, generate a new loader; the certificate authority stays the same.</p></details><button id="prepare">Prepare HTTPS</button><p id="tlsState" role="status"></p>
<div id="trustDownloads" hidden><a id="helper" class="button" href="/setup/trust/windows">Download trust helper</a><p>Run this once on the game computer after downloading:</p><code id="helperCommand"></code><details id="certificateHelp"><summary>Still getting a certificate error?</summary><a href="/setup/trust/certificate">Download certificate</a><p>SHA-256 fingerprint: <code id="fingerprint"></code></p><details><summary>Firefox: check or import the certificate</summary><p>First open the HTTPS console address with <code>/setup</code> at the end, not <code>/setup/continue</code>. If setup opens without a certificate warning, Firefox trusts it; no import is needed.</p><ol><li>Click <strong>Download certificate</strong> above to save <code>party-console-root.crt</code>.</li><li>In Firefox, open the <strong>☰ menu → Settings</strong> and search for <strong>certificates</strong>.</li><li>Click <strong>View Certificates → Authorities → Import</strong>.</li><li>Select <code>party-console-root.crt</code>, enable trust for identifying websites, and click <strong>OK</strong>.</li><li>Reopen the HTTPS <code>/setup</code> page. If it opens without a certificate warning, the check passed.</li></ol><p>To inspect an imported certificate, select Party Console in Authorities, then View. Compare its SHA-256 fingerprint with the fingerprint above.</p></details>
<details><summary>Other browser, Linux, or sandboxed client help</summary><p>Native Linux helpers support Debian/Ubuntu, Fedora-family, and Arch-family systems. Close browsers before updating trust. NSS tools may be needed: libnss3-tools on Debian/Ubuntu, nss-tools on Fedora, or nss on Arch.</p><p>Chrome/Chromium/Edge: open Settings and search for Manage certificates. Import the downloaded certificate as a trusted authority if system trust was not picked up.</p><p>Flatpak, Snap, Proton, and other distributions may use separate certificate stores. Import the public certificate in that client’s certificate manager. Native Linux Steam is recommended instead of Proton. These environments are not automatically configured or verified by this helper.</p><p>A working browser does not prove Steam trusts the certificate. Setup finishes only after the game itself connects.</p></details></details><h3>2. Check HTTPS connection</h3><p>Check that this browser trusts the secure connection. The result appears here; you will stay on this page.</p><button id="checkHttps">Check HTTPS connection</button><p id="httpsStatus" role="status"></p></div></div>
<div id="loaderArea" hidden><h3>Link your character</h3><p>Paste this code into your game client’s CODE window and click Engage.</p><p>Console address: <strong id="address"></strong></p><textarea id="code" readonly aria-label="Client loader code"></textarea><button id="copy" disabled>Copy code</button><p id="loaderHelp"></p><p id="linkStatus" role="status"></p></div></div></section>
<section><h2>Run characters fully headless</h2><p>Log out your characters from other game windows, then continue to the dashboard to run them headless. No client linking or certificate installation is needed.</p><a id="continue" class="button" href="/">Continue to dashboard</a></section></div>
<section><h2>Connection settings</h2><button id="revoke">Revoke private client connections</button> <button id="invite" hidden>Pair another browser</button><p id="invitation"></p></section></main>
<script>${setupClient}</script></body></html>`;
