"use client";
import type { LuckySlotHistory } from '../../../runtime/lucky-slot-tracking';
import type { DeconstructionMark, DeconstructionCatalog } from "./deconstruction";
import { ActiveSlot } from "./active-slot";
import { ALDataState } from "./aldata-state";
import { AppearanceChoice } from "./appearance-choice";
import { AutoCompoundMark } from "./auto-compound-mark";
import { AutoUpgradeMarks } from "./auto-upgrade-marks";
import { BankMark } from "./bank-mark";
import { BankSnapshot } from "./bank-snapshot";
import { BankVault } from "./bank-vault";
import { Bankboi } from "./bankboi";
import { BestiaryMonster } from "./bestiary-monster";
import { Char } from "./char";
import { CombatLogEntry } from "./combat-log-entry";
import { CompoundGroup } from "./compound-group";
import { FarmingPolicy } from "./farming-policy";
import { Item } from "./item";
import { Location } from "./location";
import { MerchantActivity } from "./merchant-activity";
import { MerchantBlacklistEntry } from "./merchant-blacklist-entry";
import { MerchantCatalog } from "./merchant-catalog";
import { MerchantJob } from "./merchant-job";
import { MonsterChoice } from "./monster-choice";
import { MonsterHuntState } from "./monster-hunt-state";
import { NpcSaleMark } from "./npc-sale-mark";
import { Place } from "./place";
import { PontyState } from "./ponty-state";
import { RealmControl } from "./realm-control";
import { RestockPolicy } from "./restock-policy";
import { RosterMember } from "./roster-member";
import { SkillClass } from "./skill-class";
import { StandBid } from "./stand-bid";
import { StandListing } from "./stand-listing";
import { StandPriceHistory } from "./stand-price-history";
import { StandSearchState } from "./stand-search-state";
import { StatScrollMark } from "./stat-scroll-mark";
import { SteamSwitch } from "./steam-switch";
import { UpgradeMark } from "./upgrade-mark";
import { Withdrawal } from "./withdrawal";

export type PartyState = {
  upgradeOfferingRules?: import("../../../runtime/upgrade-offerings").UpgradeOfferingRule[];
  upgradeOfferingStock?: Partial<Record<import("../../../runtime/upgrade-offerings").UpgradeOffering, number>>;
  characterAppearances?: Record<string, Pick<Char, "skin" | "characterSprite" | "characterDollHtml"> & {updatedAt:number}>;
  merchantRules?: import("../../../runtime/coordinator/inventory/shared-rules").SharedRules | null;
  gameVersion?: number;
  gameLogs?: Record<string, import("../../../runtime/game-log-filters").GameLog[]>;
  bankboiPrefix?: string;
  anniversaryAutoChat?: boolean;
  referenceRevision?: string;
  accountId?: string | null;
  passiveHunting?: import("../../../runtime/coordinator/navigation/passive-settings").PassiveSettings;
  passiveRareHunts?: { tinyp: boolean; phoenix: boolean; goldenbat?: boolean; cutebee?: boolean; hen?: boolean; rooster?: boolean };
  phoenixRouteOrder?: string[];
  rareHuntState?: {
    message?: string | null;
    encounter?: { id: string; mtype: string; stage: string; generator: string; message?: string } | null;
    patrol?: { active: boolean; paused: boolean; index: number; total: number; stage: string; message?: string; incomplete?: string[];
      regionId?: string; waypoint?: {map: string; x: number; y: number}; readyAt?: number; retryReason?: string } | null;
  };
  farmAreaState?: {
    message?: string;
    paused?: boolean;
    active?: { map: string; x: number; y: number; monsterIds?: string[] };
  };
  threshold: number;
  itemCollectionThreshold?: number;
  characters: Record<string, Char>;
  roster?: RosterMember[];
  activeSlots?: ActiveSlot[];
  characterConnections?: import('../../../runtime/roster/connection-status').CharacterConnection[];
  classChoices?: string[];
  appearanceChoices?: Record<string, AppearanceChoice[]>;
  steamSwitch?: SteamSwitch | null;
  realmControl?: RealmControl;
  marked: Record<string, BankMark[]>;
  merchantMarked?: Record<string, BankMark[]>;
  autoItemMarks?: Record<string, Record<string, "bank" | "merchant">>;
  autoUpgradeMarks?: Record<string, AutoUpgradeMarks>;
  merchantDeliveries?: Record<string, BankMark[]>;
  standListings?: StandListing[];
  npcSaleMarks?: NpcSaleMark[];
  deconstructionMarks?: DeconstructionMark[];
  autoDeconstruction?: Record<string, Record<string, { item: Item }>>;
  deconstructionCatalog?: DeconstructionCatalog;
  autoNpcSales?: Record<string, { item: Item; createdAt: number; character?: string }>;
  autoStandMarks?: Record<string, { item: Item; price: number; createdAt: number }>;
  merchantRoutinePriorities?: Record<string, number>;
  merchantBlacklist?: Record<string, MerchantBlacklistEntry>;
  merchantAutomations?: Record<string, boolean>;
  giveawayRealms?: { key: string; label: string }[];
  giveawayPlayers?: Record<string, string[]>;
  standBids?: Record<string, StandBid>;
  autoStandBuys?: boolean;
  autoBlacklistMerchants?: boolean;
  nativeStand?: { offers: Record<string, { itemId: string; auto: boolean; phase: string; slot: string; level?: number; price?: number; quantity?: number; acknowledged?: number; problem?: string }>; problems: Record<string, string> };
  standPriceHistory?: Record<string, StandPriceHistory>;
  standSearch?: StandSearchState;
  upgrades?: Record<string, UpgradeMark[]>;
  statScrolls?: Record<string, StatScrollMark[]>;
  purchases?: Record<string, { name: string }[]>;
  compounds?: Record<string, CompoundGroup[]>;
  autoCompounds?: Record<string, AutoCompoundMark[]>;
  autoExchanges?: Record<string, { name: string; level: number }>;
  goldTargets?: Record<string, number>;
  withdrawals?: Record<string, Withdrawal[]>;
  leader?: string | null;
  followers?: Record<string, boolean>;
  eventsByCharacter?: Record<string, boolean>;
  eventSelectionsByCharacter?: Record<string, string[]>;
  eventSchedules?: import("./event-selection-control").EventSchedule[];
  monsterFocus?: string[] | string;
  monsterFocusByCharacter?: Record<string, string[]>;
  monsterPrioritiesByCharacter?: Record<string, Record<string, number>>;
  monsterSearchRadiusByCharacter?: Record<string, number>;
  combatRecovery?:{phase:string;reason?:string;names:string[]}|null;
  scatterMonsterTypes?: string[];
  huntSettings?: import("../../../runtime/coordinator/hunt/settings").HuntSettings;
  huntFailures?: Record<string, {deaths: number; expirations: number}>;
  huntBlacklist?: Record<
    string,
    { monsterId: string; at: number; deaths: number; expirations?: number; reason?: string; characters?: string[] }
  >;
  farmingProfiles?: Record<string, {
    farmAreaState?: PartyState["farmAreaState"];
    farmingPolicy?: FarmingPolicy;
    monsterHunt?: MonsterHuntState | null;
    huntSettings?: import("../../../runtime/coordinator/hunt/settings").HuntSettings;
    huntBlacklist?: PartyState["huntBlacklist"];
    monsterFocus?: string[];
    location?: PartyState["partyLocation"];
  }>;
  farmingPolicy?: FarmingPolicy;
  partyFarmingMode?: "default" | "scatter";
  partyFarmingMonsterType?: string | null;
  monsterHunt?: MonsterHuntState | null;
  activeConvoy?: {
    id: string;
    phase: string;
    phaseStartedAt?: number;
    lastProgressAt?: number;
    failureCode?: string;
    failure?: string;
    legIndex?: number;
    returnLegs?: { type: "walk" | "town"; location: Location }[];
    blockers?: Record<string, { reason: string; expectedCommandId: number | null;
      reportedCommandId: number | null; expectedPhase: string; reportedPhase: string | null }>;
  } | null;
  characterLocations?: Record<string, Location>;
  partyLocation?: Location | null;
  restockPolicies?: Record<string, RestockPolicy>;
  merchantCharacter?: string | null;
  merchantForceStand?: boolean;
  merchantWeapon?: { item: Item } | null;
  luckyUpgradeSlots?: Record<string, number | null>;
  luckySlotTracking?: LuckySlotHistory;
  merchantQueue?: MerchantJob[];
  merchantCurrent?: MerchantJob | null;
  merchantActivity?: MerchantActivity[];
  combatLogs?: Record<string, CombatLogEntry[]>;
  bankSortMode?: "automatic" | "request";
  bankSortRequest?: { id: string; status: "queued" | "sorting" | "retry"; message?: string } | null;
  gatheringModes?: string[];
  gatheringNoTool?: Record<string, boolean>;
  gatheringCooldowns?: { fishing?: number; mining?: number };
  mluckSchedule?: {
    target: string;
    remainingMs: number;
    leadMs: number;
    dispatchInMs: number;
    marginMs: number;
    status: string;
  } | null;
  aldata?: ALDataState;
  ponty?: PontyState;
  merchantCatalog?: MerchantCatalog;
  bank?: BankSnapshot | null;
  bankGold?: number | null;
  bankVaults?: BankVault[];
  bankbois?: Bankboi[];
  bankboiQueue?: {
    id: string;
    item: Item;
    state: string;
    bootstrap?: boolean;
  }[];
  bankboiTransaction?: { bankboi: string; phase: string; mode: string } | null;
  travelPlaces?: Place[];
  monsterChoices?: MonsterChoice[];
  bestiaryCatalog?: BestiaryMonster[];
  skillCatalog?: SkillClass[];
  anniversary?: {
    blacklist?: string[];
    slices: string[];
    labels: Record<string, string>;
    counts: Record<string, number>;
    completeSets: number;
    nativeSlice?: string | null;
    tradableNative: number;
    missing: string[];
    live?: {
      round?: number;
      target?: string;
      map?: string;
      x?: number;
      y?: number;
      expires?: number;
      next?: number;
    } | null;
    schedule?: {
      round?: number;
      target?: string;
      map?: string;
      x?: number;
      y?: number;
      expires?: number;
      next?: number;
      live?: boolean;
    } | null;
    totalSlices?: number;
    perFlavorTarget?: number;
    tradeLimits?: Record<string, number>;
    message?: string;
    advertised?: boolean;
    craftReady?: boolean;
    crafted?: number;
    chatMessage?: string;
    chatAdvertisement?: {
      id: string;
      message: string;
      queuedAt: number;
    } | null;
    eventCycle?: {
      id: string;
      startsAt: number;
      endsAt: number;
      destination?: {
        map: string;
        x: number;
        y: number;
        label?: string;
      } | null;
      participants?: string[];
      returnDispatchedAt?: number | null;
      returnReason?: string | null;
    } | null;
    activity?: { at: number; level: string; message: string }[];
    handoffTargets?: { name: string; round: string; slice: string }[];
  };
};
